-- Run once in Supabase > SQL Editor.

create table if not exists public.site_submissions (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('contact', 'order', 'notification', 'ai_guide', 'interest', 'note')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_content (
  id text primary key,
  type text not null,
  title text not null,
  url text not null default '',
  status text not null default 'draft',
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.site_submissions enable row level security;
alter table public.admin_content enable row level security;

drop policy if exists "public can submit forms" on public.site_submissions;
create policy "public can submit forms"
on public.site_submissions for insert
to anon, authenticated
with check (true);

drop policy if exists "authenticated admins manage submissions" on public.site_submissions;
create policy "authenticated admins manage submissions"
on public.site_submissions for all
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@gal-einai.local')
with check ((auth.jwt() ->> 'email') = 'admin@gal-einai.local');

drop policy if exists "authenticated admins manage content" on public.admin_content;
create policy "authenticated admins manage content"
on public.admin_content for all
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@gal-einai.local')
with check ((auth.jwt() ->> 'email') = 'admin@gal-einai.local');

drop policy if exists "public can read published examples" on public.admin_content;
create policy "public can read published examples"
on public.admin_content for select
to anon, authenticated
using (
  type = 'example'
  and status in ('active', 'past_dates')
);

insert into storage.buckets (id, name, public)
values ('admin-uploads', 'admin-uploads', false)
on conflict (id) do update set public = false;

insert into storage.buckets (id, name, public)
values ('public-ciphers', 'public-ciphers', true)
on conflict (id) do update set public = true;

drop policy if exists "authenticated admins manage uploads" on storage.objects;
create policy "authenticated admins manage uploads"
on storage.objects for all
to authenticated
using (
  bucket_id = 'admin-uploads'
  and (auth.jwt() ->> 'email') = 'admin@gal-einai.local'
)
with check (
  bucket_id = 'admin-uploads'
  and (auth.jwt() ->> 'email') = 'admin@gal-einai.local'
);

drop policy if exists "authenticated admins manage public ciphers" on storage.objects;
create policy "authenticated admins manage public ciphers"
on storage.objects for all
to authenticated
using (
  bucket_id = 'public-ciphers'
  and (auth.jwt() ->> 'email') = 'admin@gal-einai.local'
)
with check (
  bucket_id = 'public-ciphers'
  and (auth.jwt() ->> 'email') = 'admin@gal-einai.local'
);

drop policy if exists "public can read public ciphers" on storage.objects;
create policy "public can read public ciphers"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'public-ciphers');
