-- Run once in Supabase > SQL Editor.

create table if not exists public.site_submissions (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('contact', 'order', 'notification', 'ai_guide', 'interest', 'note')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_content (
  id text primary key,
  type text not null,
  title text not null,
  url text not null default '',
  status text not null default 'draft',
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.purchased_update_access (
  id bigint generated by default as identity primary key,
  email text not null,
  purchaser_name text not null default '',
  license_code text not null default '',
  purchased_at date not null default current_date,
  expires_at date not null,
  device_limit integer not null default 2,
  devices jsonb not null default '[]'::jsonb,
  status text not null default 'active' check (status in ('active', 'blocked', 'refunded')),
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists purchased_update_access_email_idx
on public.purchased_update_access (email);

alter table public.site_submissions enable row level security;
alter table public.admin_content enable row level security;
alter table public.purchased_update_access enable row level security;

drop policy if exists "public can submit forms" on public.site_submissions;
create policy "public can submit forms"
on public.site_submissions for insert
to anon, authenticated
with check (true);

drop policy if exists "authenticated admins manage submissions" on public.site_submissions;
create policy "authenticated admins manage submissions"
on public.site_submissions for all
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@gal-einai.local')
with check ((auth.jwt() ->> 'email') = 'admin@gal-einai.local');

drop policy if exists "authenticated admins manage content" on public.admin_content;
create policy "authenticated admins manage content"
on public.admin_content for all
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@gal-einai.local')
with check ((auth.jwt() ->> 'email') = 'admin@gal-einai.local');

drop policy if exists "authenticated admins manage purchased update access" on public.purchased_update_access;
create policy "authenticated admins manage purchased update access"
on public.purchased_update_access for all
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@gal-einai.local')
with check ((auth.jwt() ->> 'email') = 'admin@gal-einai.local');

create or replace function public.check_full_update_access(p_email text)
returns table (
  is_active boolean,
  purchased_at date,
  expires_at date,
  days_left integer
)
language sql
stable
security definer
set search_path = public
as $$
  select
    coalesce(bool_or(
      status = 'active'
      and expires_at >= current_date
    ), false) as is_active,
    max(purchased_at) as purchased_at,
    max(expires_at) as expires_at,
    greatest(coalesce(max(expires_at) - current_date, -1), -1)::integer as days_left
  from public.purchased_update_access
  where lower(trim(email)) = lower(trim(p_email));
$$;

revoke all on function public.check_full_update_access(text) from public;
grant execute on function public.check_full_update_access(text) to anon, authenticated;

create or replace function public.activate_full_license(
  p_email text,
  p_license_code text,
  p_device_id text,
  p_device_name text default '',
  p_app_version text default ''
)
returns table (
  is_active boolean,
  expires_at date,
  days_left integer,
  device_count integer,
  device_limit integer,
  message text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  row_data public.purchased_update_access%rowtype;
  normalized_email text := lower(trim(coalesce(p_email, '')));
  clean_code text := trim(coalesce(p_license_code, ''));
  clean_device text := trim(coalesce(p_device_id, ''));
  next_devices jsonb;
  existing_device boolean;
begin
  if normalized_email = '' or clean_code = '' or clean_device = '' then
    return query select false, null::date, -1, 0, 2, 'missing_details';
    return;
  end if;

  select * into row_data
  from public.purchased_update_access
  where email = normalized_email
    and license_code = clean_code
  limit 1;

  if not found then
    return query select false, null::date, -1, 0, 2, 'not_found';
    return;
  end if;

  if row_data.status <> 'active' or row_data.expires_at < current_date then
    return query select false, row_data.expires_at, greatest(row_data.expires_at - current_date, -1)::integer,
      jsonb_array_length(row_data.devices), row_data.device_limit, 'inactive';
    return;
  end if;

  existing_device := row_data.devices @> jsonb_build_array(jsonb_build_object('id', clean_device));
  if not existing_device and jsonb_array_length(row_data.devices) >= row_data.device_limit then
    return query select false, row_data.expires_at, greatest(row_data.expires_at - current_date, -1)::integer,
      jsonb_array_length(row_data.devices), row_data.device_limit, 'device_limit';
    return;
  end if;

  if existing_device then
    next_devices := (
      select jsonb_agg(
        case
          when device->>'id' = clean_device then
            device || jsonb_build_object('last_seen_at', now(), 'app_version', p_app_version)
          else device
        end
      )
      from jsonb_array_elements(row_data.devices) device
    );
  else
    next_devices := row_data.devices || jsonb_build_array(jsonb_build_object(
      'id', clean_device,
      'name', left(coalesce(p_device_name, ''), 80),
      'first_seen_at', now(),
      'last_seen_at', now(),
      'app_version', left(coalesce(p_app_version, ''), 40)
    ));
  end if;

  update public.purchased_update_access
  set devices = coalesce(next_devices, '[]'::jsonb),
      updated_at = now()
  where id = row_data.id;

  return query select true, row_data.expires_at, greatest(row_data.expires_at - current_date, -1)::integer,
    jsonb_array_length(coalesce(next_devices, '[]'::jsonb)), row_data.device_limit, 'active';
end;
$$;

revoke all on function public.activate_full_license(text, text, text, text, text) from public;
grant execute on function public.activate_full_license(text, text, text, text, text) to anon, authenticated;

drop policy if exists "public can read published examples" on public.admin_content;
create policy "public can read published examples"
on public.admin_content for select
to anon, authenticated
using (
  type = 'example'
  and status in ('active', 'past_dates')
);

insert into storage.buckets (id, name, public)
values ('admin-uploads', 'admin-uploads', false)
on conflict (id) do update set public = false;

insert into storage.buckets (id, name, public)
values ('public-ciphers', 'public-ciphers', true)
on conflict (id) do update set public = true;

drop policy if exists "authenticated admins manage uploads" on storage.objects;
create policy "authenticated admins manage uploads"
on storage.objects for all
to authenticated
using (
  bucket_id = 'admin-uploads'
  and (auth.jwt() ->> 'email') = 'admin@gal-einai.local'
)
with check (
  bucket_id = 'admin-uploads'
  and (auth.jwt() ->> 'email') = 'admin@gal-einai.local'
);

drop policy if exists "authenticated admins manage public ciphers" on storage.objects;
create policy "authenticated admins manage public ciphers"
on storage.objects for all
to authenticated
using (
  bucket_id = 'public-ciphers'
  and (auth.jwt() ->> 'email') = 'admin@gal-einai.local'
)
with check (
  bucket_id = 'public-ciphers'
  and (auth.jwt() ->> 'email') = 'admin@gal-einai.local'
);

drop policy if exists "public can read public ciphers" on storage.objects;
create policy "public can read public ciphers"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'public-ciphers');
